<?php

namespace App\Service;

use App\Repositories\Contracts\TypeRepository;

class TypeService
{
    protected $typeRepository;

    public function __construct( TypeRepository $typeRepository ) { $this->typeRepository = $typeRepository; }

    public function store( array $data )
    {
        try {
            return $this->typeRepository->save( $data );
        } catch ( \Exception $exception ) {
            return [
                'error'   => true,
                'message' => $exception->getMessage()
            ];
        }
    }

    public function update( array $data, $model )
    {
        try {
            return $this->typeRepository->update( $model, $data );
        } catch ( \Exception $exception ) {
            return [
                'error'   => true,
                'message' => $exception->getMessage()
            ];
        }
    }

    public function destroy( $id )
    {
        try {
            $model = $this->typeRepository->findOneOrFail( $id );
            $this->typeRepository->delete( $model );
            return [
                'error'   => false,
                'message' => 'ExcluÃ­do com sucesso !!!'
            ];
        } catch ( \Exception $exception ) {
            return [
                'error'   => true,
                'message' => $exception->getMessage()
            ];
        }
    }

    public function all()
    {
        try {
            return $this->typeRepository->all();
        } catch ( \Exception $exception ) {
            return [
                'error'   => true,
                'message' => $exception->getMessage()
            ];
        }
    }

    public function paginate()
    {
        try {
            return $this->typeRepository->paginate();
        } catch ( \Exception $exception ) {
            return [
                'error'   => true,
                'message' => $exception->getMessage()
            ];
        }
    }

    public function findOne( $id )
    {
        try {
            return $this->typeRepository->findOne( $id );
        } catch ( \Exception $exception ) {
            return [
                'error'   => true,
                'message' => $exception->getMessage()
            ];
        }
    }
}
